# Generated by Django 4.2.7 on 2025-09-12 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Разрешить комментарии'),
        ),
        migrations.AddField(
            model_name='article',
            name='code_content',
            field=models.TextField(blank=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='article',
            name='code_language',
            field=models.CharField(blank=True, max_length=50, verbose_name='Язык кода'),
        ),
        migrations.CreateModel(
            name='ArticleScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/%Y/%m/%d/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='knowledge.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
