# Generated by Django 4.2.7 on 2025-09-12 20:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0003_articleattachment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleview',
            unique_together={('article', 'user', 'ip_address')},
        ),
    ]
