# Generated by Django 4.2.7 on 2025-09-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_alter_articleview_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='code_content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='code_language',
        ),
    ]
