# Generated by Django 4.2.7 on 2025-09-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_remove_code_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На рассмотрении'), ('published', 'Опубликовано'), ('archived', 'Архив')], default='draft', max_length=10, verbose_name='Статус'),
        ),
    ]
