# Generated by Django 4.2.7 on 2025-09-12 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('suggestion_type', models.CharField(choices=[('new_article', 'Новая статья'), ('edit_article', 'Редактирование статьи'), ('new_category', 'Новая категория'), ('edit_category', 'Редактирование категории')], max_length=20, verbose_name='Тип предложения')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('needs_revision', 'Требует доработки')], default='pending', max_length=20, verbose_name='Статус')),
                ('moderator_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Теги')),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=1, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Автор предложения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='knowledge.category', verbose_name='Категория')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('target_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_suggestions', to='knowledge.article', verbose_name='Целевая статья')),
            ],
            options={
                'verbose_name': 'Предложение контента',
                'verbose_name_plural': 'Предложения контента',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('suggestion_approved', 'Предложение одобрено'), ('suggestion_rejected', 'Предложение отклонено'), ('suggestion_revision', 'Требуется доработка'), ('new_comment', 'Новый комментарий'), ('article_updated', 'Статья обновлена')], max_length=30, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='Тип связанного объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Одобрено'), ('reject', 'Отклонено'), ('request_revision', 'Запрошена доработка'), ('edit', 'Отредактировано'), ('delete', 'Удалено')], max_length=20, verbose_name='Действие')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата действия')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='moderation.contentsuggestion', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Лог модерации',
                'verbose_name_plural': 'Логи модерации',
                'ordering': ['-created_at'],
            },
        ),
    ]
