# Generated by Django 4.2.7 on 2025-09-15 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0008_alter_article_content'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.contentsuggestion'),
        ),
        migrations.AlterField(
            model_name='contentsuggestion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentsuggestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.category'),
        ),
        migrations.AlterField(
            model_name='contentsuggestion',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentsuggestion',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='contentsuggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('article', 'Статья'), ('category', 'Категория'), ('tag', 'Тег'), ('other', 'Другое')], max_length=20, verbose_name='Тип предложения'),
        ),
        migrations.AlterField(
            model_name='contentsuggestion',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='contentsuggestion',
            name='target_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.article'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('approve', 'Одобрено'), ('reject', 'Отклонено'), ('request_revision', 'Запрошена доработка'), ('comment', 'Добавлен комментарий'), ('status_change', 'Изменен статус')], max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='moderation.contentsuggestion'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('suggestion_approved', 'Предложение одобрено'), ('suggestion_rejected', 'Предложение отклонено'), ('suggestion_revision', 'Требуется доработка'), ('moderation_assigned', 'Назначена модерация'), ('system', 'Системное уведомление')], max_length=30, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
