# Generated by Django 4.2.7 on 2025-09-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_remove_notification_related_object_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content_object',
            new_name='suggestion',
        ),
        migrations.AlterField(
            model_name='contentsuggestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='contentsuggestion',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Модерировано'),
        ),
        migrations.AlterField(
            model_name='contentsuggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('article', 'Статья'), ('category', 'Категория'), ('tag', 'Тег'), ('edit', 'Редактирование')], max_length=20, verbose_name='Тип предложения'),
        ),
        migrations.AlterField(
            model_name='contentsuggestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('created', 'Создано'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('needs_revision', 'Требует доработки'), ('edited', 'Отредактировано'), ('deleted', 'Удалено')], max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('suggestion_approved', 'Предложение одобрено'), ('suggestion_rejected', 'Предложение отклонено'), ('suggestion_needs_revision', 'Предложение требует доработки'), ('new_suggestion', 'Новое предложение'), ('moderation_required', 'Требуется модерация'), ('system', 'Системное уведомление')], max_length=30, verbose_name='Тип уведомления'),
        ),
    ]
